### PR TITLE
Add media endpoints to config

### PR DESCRIPTION
**Pull request by CharlieRoseMarie**

### CODE REVIEW

**Comment by CharlieRoseMarie** [comment]
Sorry, wrong repo.

**Comment by voxpelli** [comment]
I really should get this in there though @CharlieRoseMarie 😝

**Comment by CharlieRoseMarie** [comment]
I've got a few more changes, if you want! I'll send a PR when I have them more stable.

Excellent work on the server, by the way!

**Comment by voxpelli** [comment]
Would love to @CharlieRoseMarie! I’m a bit behind on getting this repo updated so a Par would be much appreciated :)

**Pull request closed without merging**
